#!/usr/bin/with-contenv sh

#run the default config script
sh /srv/config.sh

#create folders on config
mkdir -p /srv/madsonic/config/playlists/import
mkdir -p /srv/madsonic/config/playlists/export
mkdir -p /srv/madsonic/config/playlists/backup
mkdir -p /srv/madsonic/data/transcode

#chown the madsonic directory by the new user
chown mediadepot:mediadepot -R /srv/madsonic

#copy transcode to config directory - transcode directory is subdir of path set from --home flag, do not alter
cp -R /srv/madsonic/transcode_lib/transcode/* /srv/madsonic/data/transcode/

# Force Madsonic to run in foreground
sed -i 's|-jar madsonic-booter.jar > \${LOG} 2>\&1 \&|-jar /srv/madsonic/app/madsonic-booter.jar > \${LOG} 2>\&1|g' /srv/madsonic/app/madsonic.sh

# run Madsonic
exec s6-setuidgid mediadepot /srv/madsonic/app/madsonic.sh \
  --home=/srv/madsonic/data \
  --context-path=/ \
  --default-music-folder=/mnt/music \
  --default-podcast-folder=/mnt/music \
  --default-upload-folder=/mnt/downloads \
  --default-transcode-folder=/srv/madsonic/data/transcode \
  --default-playlist-import-folder=/srv/madsonic/config/playlists/import \
  --default-playlist-export-folder=/srv/madsonic/config/playlists/export \
  --default-playlist-backup-folder=/srv/madsonic/config/playlists/backup \
  --port=8080
